---
name: Create a server list
run-name: Create Server List
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "the env"
        options:
          - "prod"
          - "dev"
jobs:
  get-instances:
    runs-on: ubuntu-latest
    steps:
      - name: Installing gcloud
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'