---
name: Create a server list
run-name: Create Server List
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "the env"
        type: choice
        options:
          - "prod"
          - "dev"
jobs:
  get-instances:
    runs-on: ubuntu-latest
    steps:
      - name: Installing gcloud
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: Activate authentication account
        run: gcloud auth activate-service-account ${{ secrets.GCP_ACCOUNT }}
      - name: Setting authentication account
        run: gcloud config set account ${{ secrets.GCP_ACCOUNT }}
      - name: Fetching vm instances
        run: |
          gcloud compute instances list --project "wise-shell-330415" --zones "us-central1-a"
