name: Github Code download
on:
  workflow_dispatch
jobs:  
  code-download:
    runs-on: ubuntu-latest
    steps:    
     - name: Download code
       uses: actions/checkout@v3
       with:
          ref: 'master'
     - name: Getting file differences
       shell: bash
       run: |
          echo "File List is.............."
          git checkout main
          git diff ^head head > filediff.txt
          echo "File List is..............Completed"
          cat filediff.txt
          while read LINE  
          do  
            echo $LINE  
          done < filediff.txt      