name: Github Code download
on:
  workflow_dispatch
jobs:  
  code-download:
    runs-on: ubuntu-latest
    steps:    
     - name: Download code
       uses: actions/checkout@v3
       with:
          ref: 'master'
          fetch-depth: 0
     - name: Getting files from GIT repo
       shell: bash
       run: |
          echo "File List is.............."
          echo "$GITHUB_WORKSPACE"
          git ls-tree -r --name-only master|grep -E 'abcdef.txt|codedownload.yml'>filepath.txt
          cat filepath.txt
          while read file_name_match
          do
            echo $file_name_match
          done